### PR TITLE
Add ads under reply box.

### PR DESCRIPTION
**Pull request by noriods**
This PR adds a field in the admin where you can put ad-code for ads you'd like to show under the reply box. Please let me know if there's anything that can be improved to get this PR accepted.

### CODE REVIEW

**Comment by noriods** [comment]
I was missing the setting in the listener that grabs the settings from the DB. It's now working properly on my website. (I just assumed it was a cache thing! 🙄)

**Comment by noriods** [comment]
@luceos I'm noticing some conflicts between this and the way Flarum handles replying. I need to move the ad-spot. Please don't merge just yet. (I'm actively testing it on my production forum.)

**Comment by luceos** [comment]
I totally missed this one 😊 

I'm going over all extensions after beta 8 has been released. With this one somewhere at the top of the list.

**Comment by luceos** [comment]
Feel free to create a new one if you're interested 👍

**Pull request closed without merging**
