### PR TITLE
add ukrainian locale file

### PR DESCRIPTION
**Pull request by dshovchko**

### CODE REVIEW

**Comment by dshovchko** [comment]
I have added a parameter for specifying the position from which to start to show the ads



admin



forum

**Review by luceos — CHANGES_REQUESTED** [review]
Hello @dshovchko and thanks for this PR. Although the changes would have been very much mergeable, I currently cannot due to the follow reasons:

- Locale ánd feature changes in one PR, we'd like to keep them separated.
- The locale changes are fine.
- The changes to add the "start from" logic was added in the dist folder, this is a compiled version of javascript in the src folder. If you want to implement this, you'd have to modify the javascript in the src folder and the re-compile using Gulp.
- Your new setting variable will never be distributed to the forum frontend because it's not registered in the `Listeners\LoadSettingsFromDatabase`.

Could you first please PR the Ukrainian locale and then submit a PR for the "start from post" logic?

Thanks, great work though and love the idea.

**Comment by dshovchko** [comment]
> The changes to add the "start from" logic was added in the dist folder, this is a compiled version of javascript in the src folder. If you want to implement this, you'd have to modify the javascript in the src folder and the re-compile using Gulp

I understand. I will do it!

> Your new setting variable will never be distributed to the forum frontend because it's not registered in the Listeners\LoadSettingsFromDatabase

It has been done.

> Could you first please PR the Ukrainian locale and then submit a PR for the "start from post" logic?

How do I do that? Revert the last commit?

**Comment by luceos** [comment]
Yes that's problematic. Under normal circumstances you create a branch for each feature and then PR those against the upstream (source). If you can fulfil the requirements I set out I'll gladly accept the combined PR though.

**Comment by dshovchko** [comment]
I will do everything in the right way

**Pull request closed without merging**
